---
- name: starter tasks
  hosts: all
  vars:
    target_env: "{{ lookup('env', 'target') }}"
  tasks:
  - include_role:
      name: "{{ name }}"
    loop:
    - update-apt-sources-1.0.0
    - disable-apt-jobs-1.0.0
    - disable-motd-1.0.0
    - app-agent-1.0.6
    - appctl-1.2.5
    - arping-1.0.5
    - caddy-1.1.8
    - jq-1.0.9
    - netcat-openbsd-1.0.4
    - starter
    loop_control:
      loop_var: name
