---
- name: copy files
  copy:
    src: files/opt/
    dest: /opt/
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: install confd files
  include_role:
    name: confd-files-1.0.9
